[package]
name = "circle_punch"
version = "0.1.0"
authors = ["e.karavskii <karavzeka@gmail.com>"]
build = "build.rs"

[dependencies]
websocket = "0.20.2"
chrono = "0.4.0"
jconfig = "0.1.0"
serde = "1.0.21"
serde_json = "1.0.6"
serde_derive = "1.0.21"
rand = "0.3"
cgmath = "0.16.0"